//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations
    {
        public int VacationID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int EmpID { get; set; }
    
        public virtual Emps Emps { get; set; }
    }
}
